### ISSUE TITLE
Facility getting error page when attempting to make changes to ES data

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/geco#533]
No Raygun crash reports received.

External user reported via email and Jing confirmed the error:

![thumbnail_image005](https://user-images.githubusercontent.com/737326/162261402-46dc9b3a-1055-4164-9b2a-c43ccf422021.png)
![thumbnail_image003](https://user-images.githubusercontent.com/737326/162261461-afc3eff4-f6d1-4de5-9f41-dbadf7e270a2.jpg)

**Comment by dougwaldron** [comment]
Exception thrown at:

https://github.com/gaepdit/geco/blob/1ff2e12b2461c562d01b09b9aa7305d6350dd5a1/GECO/ES/Form.aspx.vb#L288

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index and length must refer to a location within the string.
Parameter name: length
  Source=mscorlib
  StackTrace:
   at System.String.Substring(Int32 startIndex, Int32 length)
   at GECO.es_form.LoadESSchema() in D:\projects\geco\GECO\ES\Form.aspx.vb:line 288
   at GECO.es_form.Page_Load(Object sender, EventArgs e) in D:\projects\geco\GECO\ES\Form.aspx.vb:line 51

  This exception was originally thrown at this call stack:
    [External Code]
    GECO.es_form.LoadESSchema() in Form.aspx.vb
    GECO.es_form.Page_Load(Object, System.EventArgs) in Form.aspx.vb
    [External Code]
```

**Comment by dougwaldron** [comment]
Raygun not receiving error reports. See https://github.com/gaepdit/EPD-IT/issues/80
